# Usa la imagen oficial de Node.js
FROM node:22


ENV NODE_VERSION 22.14.0


WORKDIR /app

# Copia los archivos de package.json e instala dependencias
COPY package.json package-lock.json ./
RUN npm install

# Copia el resto de la aplicación
COPY . .


EXPOSE 5173


CMD ["npm", "run", "dev"]

